# Generated by Django 4.1.4 on 2023-01-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfulAi_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userdat',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
